### PR TITLE
Bulk action to execute actions for assets added

### PR DESCRIPTION
**Pull request by tommygonzaleza**

### CODE REVIEW

**Comment by tommygonzaleza** [comment]
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3699

**Comment by tommygonzaleza** [comment]
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3387

**Comment by tommygonzaleza** [comment]
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3963

**Comment by tommygonzaleza** [comment]
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4002

**Review by alesanchezr — APPROVED** [review]

**Pull request merged**
